# API 认证配置文件
# 用于配置各种 API 的认证信息

# BMC API 认证配置
bmc_api:
  type: "api_key"
  header_name: "X-API-Key"
  key_env: "BMC_API_KEY"
  description: "BMC 数据管理 API 的认证密钥"

# 其他 API 认证配置示例
weather_api:
  type: "bearer"
  token_env: "WEATHER_API_TOKEN"
  description: "天气 API 的 Bearer Token"

user_api:
  type: "basic"
  username: "admin"
  password_env: "USER_API_PASSWORD"
  description: "用户 API 的基本认证"

# 全局认证配置
global:
  # 默认超时时间
  timeout: "30s"
  
  # 重试配置
  retry:
    max_attempts: 3
    backoff_delay: "1s"
  
  # 缓存配置
  cache:
    enabled: true
    ttl: "5m"
