server:
  port: 8088
  host: "0.0.0.0"
  mode: "stdio"  # 可选值: "websocket" 或 "stdio"

global:
  timeout: 60s
  max_request_size: "10MB"
  default_headers:
    User-Agent: "MCP2REST/1.0"
    Accept: "application/json"
