server:
  port: 8088
  host: "0.0.0.0"
  mode: "sse"  # SSE 模式专用

global:
  timeout: 60s
  max_request_size: "10MB"
  default_headers:
    User-Agent: "MCP2REST-SSE/1.0"
    Accept: "application/json"
